# Generated by Django 4.1.5 on 2023-03-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_notification_user_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
