# Generated by Django 4.1.5 on 2023-03-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_property_comment',
        ),
    ]
