# Generated by Django 4.1.5 on 2023-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertycomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='host_to_user_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
